"""init

Revision ID: 2bb59d953705
Revises: 
Create Date: 2025-12-15 13:13:36.815840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb59d953705'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matakuliah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_mk', sa.Text(), nullable=False),
    sa.Column('nama_mk', sa.Text(), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matakuliah')),
    sa.UniqueConstraint('kode_mk', name=op.f('uq_matakuliah_kode_mk'))
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index', table_name='models', mysql_length=255)
    op.drop_table('models')
    op.drop_table('matakuliah')
    # ### end Alembic commands ###
